Write-Progress -Activity 'Configurando OCS Inventory-NG' -Completed
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "#OCS Inventory"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "10.242.6.14		ocsinventory-ng"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "#MARIProject"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "10.242.6.21		vmpwk8ap01"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "#SAP"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "10.242.7.11		vmpw8ksa01"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "#TimeSheetSP"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "10.242.4.35		time2.geravd.com.br"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "#EPM"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "10.242.4.35		epmpmo.geravd.com.br"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "#WinCVS"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "192.168.2.6		cvs.clsoftware.com.br"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "#TFS"
ac -Encoding UTF8  "$($env:windir)\system32\Drivers\etc\hosts" "192.168.2.18	tfs.geravd.com.br"